#!/usr/bin/env python3
"""
Generalize the id12 9-compression obstruction to ALL trivial-mod-9 families.

Key observation: for L=333 and the 9-compression, the target PAF sum (-74 for
s=1..8) and the forced squared norm (594) depend ONLY on L and the modulus 9 --
NOT on the family.  The ONLY family-dependent ingredient is the column-sum value
set V_H, which is determined by the K37-orbit sizes of Z_37 (K37 = image of H
mod 37):  atilde_j = eps0*1 + sum_k eps_k*|orbit_k|.

So the obstruction is: is there a compressed pair (atilde,btilde) in V_H^9 with
row sums +-1 and PAF_atilde(s)+PAF_btilde(s) = -74 (s=1..8)?  (Squared norm 594
is then automatic.)  If NO -> the family is impossible.

This applies to families with trivial image mod 9 (so that the 9-compression's
columns are the natural K37-invariant Z_37 blocks).  Among the OPEN families
(0..10) these are: id0 (r37=1), id1 (r37=2), id6 (r37=4), id8 (r37=6); plus the
now-closed id12 (r37=9) as a self-check.

For each we compute V_H, then the number of 18-term V_H^2 multisets summing to
594.  If 0 -> immediately infeasible.  Otherwise we exhaust/decide the compressed
problem when V_H is sparse enough; if V_H is dense (e.g. all odd values), the
9-compression does not close the family and we say so honestly.
"""
import itertools
import json
import os
import sys
from math import gcd

sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "code"))
from core import L, KERNEL3, all_subgroups, orbits_on_ZL, reduce_subgroup   # phase-1
from search_common import subgroup_by_id


def k37_orbit_sizes(H):
    K = reduce_subgroup(H, 37)
    seen = [False] * 37
    sizes = []
    for x in range(37):
        if seen[x]:
            continue
        o = set(); st = [x]
        while st:
            y = st.pop()
            if y in o:
                continue
            o.add(y)
            for h in K:
                st.append((h * y) % 37)
        for y in o:
            seen[y] = True
        sizes.append(len(o))
    return sorted(sizes), len(K)


def value_set(orbit_sizes):
    """Reachable values of sum_k eps_k*size_k, eps_k in {+-1}, via DP (not 2^n)."""
    reach = {0}
    for s in orbit_sizes:
        reach = {v + s for v in reach} | {v - s for v in reach}
    return sorted(reach)


def square_multisets(V, total=594, slots=18):
    sq = sorted({v * v for v in V})
    sols = []

    def rec(idx, sl, ss, cur):
        if idx == len(sq):
            if sl == 0 and ss == 0:
                sols.append({sq[i]: cur[i] for i in range(len(sq)) if cur[i]})
            return
        for n in range(sl + 1):
            if n * sq[idx] > ss:
                break
            rec(idx + 1, sl - n, ss - n * sq[idx], cur + [n])
    rec(0, slots, total, [])
    return sols


def paf9(v, s):
    return sum(v[j] * v[(j + s) % 9] for j in range(9))


def gen_sequences_pruned(V, max_sqsum=594, cap=8_000_000):
    """All length-9 sequences over V with row sum +-1 and square-sum <= max_sqsum,
    generated by DFS pruned on the running square sum.  Yields (tuple, sqsum).
    Aborts (returns None) if more than `cap` sequences would be produced."""
    Vs = sorted(V, key=lambda x: x * x)          # small squares first
    out = []
    cur = [0] * 9
    overflow = [False]

    def rec(pos, sqsum, rsum):
        if overflow[0] or sqsum > max_sqsum:
            return
        if pos == 9:
            if rsum in (-1, 1):
                out.append((tuple(cur), sqsum))
                if len(out) > cap:
                    overflow[0] = True
            return
        if sqsum + (9 - pos) * 1 > max_sqsum:
            return
        for v in Vs:
            cur[pos] = v
            rec(pos + 1, sqsum + v * v, rsum + v)
    rec(0, 0, 0)
    return None if overflow[0] else out


def decide_compressed(V, cap=8_000_000):
    """Complete decision of: atilde,btilde in V^9, row sums +-1,
    PAF_atilde(s)+PAF_btilde(s) = -74 (s=1..8).  The squared norm is forced to
    594, so we enumerate each sequence with square-sum <= 594 (pruned DFS) and
    match A/B by square-sum complement (=594) and PAF profile (=-74).
    Returns a dict; 'decided' False only if the pruned enumeration exceeds `cap`.
    """
    msets = square_multisets(V)
    if not msets:
        return {"decided": True, "feasible": False,
                "reason": "no 18-square multiset sums to 594",
                "num_square_multisets": 0}
    M = max(abs(v) for v in V)
    if sorted(V) == [x for x in range(-M, M + 1) if x % 2]:
        return {"decided": False, "feasible": None,
                "reason": "value set = all odd integers in [-%d,%d] (weak "
                          "free-odd relaxation); 9-compression does not close it"
                          % (M, M),
                "num_square_multisets": len(msets), "V_size": len(V)}
    seqs = gen_sequences_pruned(V, 594, cap=cap)
    if seqs is None:
        return {"decided": False, "feasible": None,
                "reason": f"pruned enumeration exceeds cap {cap} "
                          f"(value set too dense for direct decision)",
                "num_square_multisets": len(msets)}
    # index A-sequences by (square-sum, paf-profile)
    from collections import defaultdict
    idx = defaultdict(list)
    for v, sq in seqs:
        prof = tuple(paf9(v, s) for s in range(1, 9))
        idx[(sq, prof)].append(v)
    feasible = False
    witness = None
    for vb, sqb in seqs:
        need_sq = 594 - sqb
        if need_sq < 0:
            continue
        need_prof = tuple(-74 - paf9(vb, s) for s in range(1, 9))
        hit = idx.get((need_sq, need_prof))
        if hit:
            feasible = True
            witness = (list(hit[0]), list(vb))
            break
    return {"decided": True, "feasible": feasible,
            "num_square_multisets": len(msets),
            "num_pruned_sequences": len(seqs),
            "witness": witness}


def main():
    # classify: which surviving/open families are trivial mod 9?
    open_ids = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12]
    out = []
    for sid in open_ids:
        H, rec = subgroup_by_id(sid)
        r9 = len(reduce_subgroup(H, 9))
        if r9 != 1:
            out.append({"id": sid, "order": len(H), "trivial_mod9": False,
                        "note": "9-compression obstruction (this form) needs "
                                "trivial mod 9; skipped"})
            continue
        sizes, r37 = k37_orbit_sizes(H)
        V = value_set(sizes)
        dec = decide_compressed(V)
        row = {"id": sid, "order": len(H), "trivial_mod9": True,
               "r37": r37, "k37_orbit_sizes": sizes, "value_set_V": V,
               "decision": dec}
        if dec.get("decided") and dec.get("feasible") is False:
            row["verdict"] = "IMPOSSIBLE by 9-compression (value-set restricted)"
        elif dec.get("decided") and dec.get("feasible") is True:
            row["verdict"] = "9-compression FEASIBLE (does not close; not a proof)"
        else:
            row["verdict"] = "9-compression inconclusive by this method"
        out.append(row)
    res = {"L": L, "compression_modulus": 9,
           "family_independent_targets": {"PAF_sum_s_ne_0": -74,
                                          "forced_squared_norm": 594},
           "families": out}
    outp = os.path.join(os.path.dirname(__file__), "..", "results",
                        "general_compression.json")
    json.dump(res, open(outp, "w"), indent=2)
    for r in out:
        if r.get("trivial_mod9"):
            print(f"id{r['id']:>2} order={r['order']:>3} r37={r['r37']:>2} "
                  f"|V|={len(r['value_set_V']):>2} -> {r.get('verdict')}")
        else:
            print(f"id{r['id']:>2} order={r['order']:>3} (not trivial mod 9; skipped)")
    print("wrote", outp)


if __name__ == "__main__":
    main()
